services:
  all_in_one:
    build:
      context: .
      args:
        APT_PROFILE: ${APT_PROFILE:-normal}
    container_name: nc_migration_all_in_one
    ports:
      - "${PORT}:80"
      - "6379:6379"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      DB_TYPE: ${DB_TYPE}
    volumes:
      - ${CONFIG_DIR}:/var/www/html/nextcloud/config
      - ${APPS_DIR}:/var/www/html/nextcloud/custom
      - ${FILES_DIR}:${FILES_DIR_CONTAINER}
      - ${DB_DUMP_DIR}:/mnt/mysql
      - ${REDIS_DIR}:/mnt/redis
