services:
  all_in_one:
    build: .
    container_name: nc_migration_all_in_one
    ports:
      - "8080:80"
      - "6379:6379"
    environment:
      - NC_TRUSTED_DOMAINS=localhost
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./nextcloud_config:/mnt/NextCloud/config
      - ./nextcloud_apps:/var/www/html/nextcloud/custom
      - ./nextcloud_files:/mnt/NextCloud/files
      - ./nextcloud_sessions:/mnt/NextCloud/sessions
      - ./mysql:/mnt/mysql
      - ./redis:/mnt/redis
